# Generated by Django 2.2.5 on 2019-09-22 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
