# Generated by Django 2.2.5 on 2019-09-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0006_post_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
